---
- name: Delete and stop Apache HTTPD
  hosts: all
  tasks:
    - name: Unconfiguration firewall
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled
    - name: httpd is stopped
      service:
        name: httpd
        state: stopped
        enabled: no
    - name: Delete File
      file:
        path: /var/www/html/index.html
        state: absent
    - name: package Delete
      yum:
        name: httpd
        state: absent

