---
- name: 사용자 삭제 예제
  hosts: devservers
  vars_files:
    - vars/secret.yml
  tasks:
    - name: 사용자 삭제 작업
      user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
        state: absent
        remove: yes
      with_items: "{{ newusers }}"